apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledgr
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Iftisam-sandik/secure-gitops-devsecops-eks.git
    targetRevision: main
    path: helm/ledgr
    helm:
      releaseName: ledgr

  destination:
    server: https://kubernetes.default.svc
    namespace: ledgr

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
