apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USER: {{ .Values.mysql.user | quote }}
  DB_NAME: {{ .Values.mysql.database | quote }}
  PORT: {{ .Values.backend.service.port | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
