apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  annotations:
    "helm.sh/resource-policy": keep
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.storage.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
