apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.storage.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
